Support localization.
insenseanalytics/laravel-nova-permission pull request #4
Opened 2018-12-14 08:37 UTC by jianminLee

Hi,I have localized support for this package, and it now supports localized languages ​​for permission searches. I have modified the README.md instructions.

2018-12-14 13:08 UTC, paras-malhotra commented
@jianminLee thanks for the PR. I've requested 2 changes. Once you make the changes, will merge.

2018-12-14 13:10 UTC, paras-malhotra requested changes

2018-12-14 13:10 UTC, paras-malhotra commented on resources/lang/zh-CN/navigation.php
> +return [
Let's keep all lang files (except en) outside of the package. The user can always create these in their applications after they publish.

2018-12-14 13:10 UTC, paras-malhotra commented on src/PermissionResourceTrait.php
> +        $trans_search = array_keys(preg_grep("/$search/",array_dot(__('laravel-nova-permission::permissions.display_names'))));
This is also best left for the user's application.

2018-12-14 13:10 UTC, paras-malhotra commented on src/PermissionResourceTrait.php
> +            })->canSee(function (){
I think you'll need to correct indentation in all the changes you've made

2018-12-15 01:35 UTC, jianminLee commented on src/PermissionResourceTrait.php
> +        $trans_search = array_keys(preg_grep("/$search/",array_dot(__('laravel-nova-permission::permissions.display_names'))));
I do not quite understand you. If you remove the applySearch function, users will not be able to search for permissions through localized languages. Its existence will support "permission name" and "localization" searches.

2018-12-16 12:50 UTC, merged

2018-12-16 13:31 UTC, paras-malhotra commented
@jianminLee thanks for the PR. I have merged it but we are not supporting translated search in the package for now. If you need it, you can add your own Role Resource and Permission Resource classes. See https://github.com/insenseanalytics/laravel-nova-permission/commit/dbf7ef7e36fafcd5f5e4f25b3084b690824d78d9 for changes.